### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by OfficialFluX** [NexusByte/AntiCheatPro#1]
ab 10 klicks ''autoklicker''

**Comment by NexusByte** [comment]
Ist es möglich ein Video von dem Bug zu schicken?

**Comment by OfficialFluX** [comment]
Ne


Am 04.03.2017 20:15 schrieb "Lennart" <notifications@github.com>:

**Comment by NexusByte** [comment]
Es gibt zurzeit aber keine Autoklicker Detection.
